config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  get "/about", to: "homes#about"
  get "/admin", to: "admin/homes#top"


  devise_for :customers,skip: [:passwords,], controllers: {
    sessions:      'customer/sessions',
    registrations: 'customer/registrations'
    }


  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions:      'admin/sessions',
    }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope module: :customer do
    get "customers/my_page" => "customers#show", as: "my_page"
    post "orders/comfirm" => "orders#comfirm"
    get "orders/comfirm" => "orders#comfirm"
    #post "orders/create" => "orders#create", as: "orders/complete"
    get "orders/complete" => "orders#complete"
    post "orders/complete" => "orders#complete"
    post "orders/new" => "orders#new"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    delete "cart_items/destroy" => "cart_items#destroy"
    get "item/index" => "items#serch",as: "serch"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    patch "addresses/:id/edit" => "addresses#edit"
    resources :items,only: [:index,:show,:delete,:update]
    resources :customers,only: [:show,:edit,:update,:unsubscribe,:withdraw]
    resources :addresses,only: [:index,:create,:edit,:destroy,:update]
    resources :cart_items,only: [:index,:create,:update,:destroy]
    resources :orders,only: [:new,:create,:index,:show]
  end

   namespace :admin do
    resources :homes,only: [:top]
    resources :genres,only: [:index,:show, :edit, :update,:create]
    resources :items,only: [:new,:index,:create,:show,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :addresses

  has_many :orders

  def full_name
    this.last_name + this.first_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
    @customer = Customer.find_by(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @subtotal = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
    @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal } + 800
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses= current_customer.addresses.all
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save
    redirect_to addresses_path
  end

  def update
    @address = Address.find(params[:id])
    @address.customer_id = current_customer.id
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    address = Address.find(params[:id])
    ba
    address.destroy
    redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:postal_code,:address, :name)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  def index
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end

  def update
    @cart_items = CartItem.find(params[:id])
    @cart_items.update(cart_item_params)
    redirect_to cart_items_path
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @cart_item.save
    redirect_to cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
   current_customer.cart_items.destroy_all
   redirect_to cart_items_path
  end

   private

  def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

  def show
    @customer=current_customer
  end

  def edit
    @customer=current_customer
  end

  def update
    @customer=current_customer
    @customer.update(customer_params)
    redirect_to customer_path
  end

  def unsubscribe
    @customer=current_customer
  end

  def withdraw
    #customerの退会ステータスをfalseに更新
     @customer=current_customer
     @customer.update(is_deleted: true)
     reset_session
     redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @genres=Genre.all
    @items=Item.all
  end

  def serch
    @genres=Genre.all
    @items=Item.all
    if params[:genre_id]
      @genre=Genre.find(params[:genre_id])
      @items=@genre.items
    end
  end

  def show
    @genres=Genre.all
    @item=Item.find(params[:id])
    @cart_item=CartItem.new
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  def new
    @order = Order.new
    @customer = current_customer
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @subtotal = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
    @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal } + 800
  end

  def comfirm
    @order = Order.new(order_params)
    if params[:order][:address_number] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_number] == "2"
      address = Address.find(params[:order][:address_id])
      @order.postal_code = address.postal_code
      @order.address = address.address
      @order.name = address.name
    elsif params[:order][:address_number] == "3"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
      @address = Address.new(
                  postal_code: params[:order][:postal_code],
                  address: params[:order][:address],
                  name: params[:order][:name],
                  customer_id: current_customer.id
                  )
      @address.save
    end
    @cart_items = CartItem.where(customer_id: current_customer.id)
    @subtotal = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price } + 800
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = Order.new(order_params)
    @customer = current_customer
    @order.customer_id = current_customer.id
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart_item.amount
        order_detail.price = cart_item.item.price
        order_detail.save!
      end
       cart_items.destroy_all
       redirect_to orders_complete_path
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def complete
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :total_payment)
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end



  # The path used after sign up.
  def after_sign_up_path_for(resource)
    my_page_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def after_sign_in_path_for(resource)
    items_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected

  def customer_state
   @customer = Customer.find_by(email: params[:customer][:email])
   return if !@customer
   if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == false)
     customer_path(@customer.id)
   else
     redirect_to new_customer_registration_path
   end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/customer/orders/comfirm.html.erb
<div class="container">
 <h4>注文情報確認</h4>
 <div class="row">
   <div class="col-lg-8">
    <table class="table table-striped">
     <thead>
     <tr>
      <td>商品名</td>
      <td>単価（税込）</td>
      <td>数量</td>
      <td>小計</td>
     </tr>
    </thead>
    <tbody>
     <% @cart_items.each do |cart_item| %>
     <tr>
      <td><%= cart_item.item.name %></td>
      <td><%= cart_item.item.with_tax_price %></td>
      <td><%= cart_item.amount %></td>
      <td><%= cart_item.subtotal %></td>
     </tr>
     <% end %>
    </tbody>
    </table>
   </div>
   <div class="col-lg-4">
    <table class="table table-striped">
     <tr>
      <td>送料</td>
      <td>800円</td>
     </tr>
     <tr>
      <td>商品合計</td>
      <td><%= @subtotal.round.to_s(:delimited)%></td>
     </tr>
     <tr>
      <td>請求金額</td>
      <td><%= @total.round.to_s(:delimited)%></td>
     </tr>
    </table>
   </div>
 </div>
 <div class="row">
  <div class="col-lg-12">
   <strong>支払い方法</strong>
   <p><%= @order.payment_method_i18n %></p>
   <strong>お届け先</strong>
   <%# byebug %>
   <p>〒<%= @orderpostal_code %>　<%= @order.address %>　<%= @order.name %></p>
  </div>
 </div>
 <div style=" display: flex: center">
  <p>
   <%= form_with model: @order, url: orders_path do |f| %>
   <%= f.hidden_field :name %>
   <%= f.hidden_field :address %>
   <%= f.hidden_field :total_payment, value: @total %>
   <%= f.hidden_field :payment_method %>
   <%= f.submit "注文を確定する" %>
   <% end %>
  </p>
 </div>
</div>

app/views/customer/orders/complete.html.erb
<div style=" display: flex; align-items: center; width: auto; height: 500px; justify-content: center;">
  <h2>ご注文ありがとうございます</h2>
</div>

app/views/customer/orders/index.html.erb
<div class="container">
 <div class="row">
   <div class="col-lg-12"><h4>注文履歴一覧</h4></div>
 </div>
 <div class="row">
  <div class="col-lg-12">
   <table class="table table-striped">
     <thead>
      <tr>
        <td>注文日</td>
        <td>配送先</td>
        <td>注文商品</td>
        <td>支払い金額</td>
        <td>ステータス</td>
        <td>注文詳細</td>
      </tr>
     </thead>
     <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        <td><%= order.address %><br>
        <%= order.name %></td>
        <td><% order.order_details.each do |order_detail| %>
        <%= order_detail.item.name %><br>
        <% end %></td>
        <td><%= (order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal } + 800).round.to_s(:delimited) %></td>
        <td></td>
        <td><%= button_to "表示する", order_path(order.id),method: :get %></td>
      </tr>
      <% end %>
     </tbody>
   </table>
  </div>
 </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container">
  <h4>注文情報入力</h4>
  <div class="row">
   <div class="col-md-12">
    <table class="table table-striped">
    <%= form_with model: @order, url: orders_comfirm_path, method: :post do |f| %>

    <strong>支払い方法</strong>
     <p><%= f.radio_button :payment_method, Order.payment_methods.key(0) %>
        <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %></p>
     <p><%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
        <%= f.label :payment_method, Order.payment_methods_i18n[:transfer]%></p>
    <strong>お届け先</strong>
    <p>
     <%= f.radio_button :address_number, 1 %>
     <%= f.label :address_number, "ご自身の住所" %>
     <p><%= @customer.address %></p>
     <p><%= @customer.last_name %><%= @customer.first_name %></p>
    </p>
    <p>
     <%= f.radio_button :address_number, 2 %>
     <%= f.label :address, "登録済住所から選択" %>
    </p>
    <p><%= f.select :address_id, options_from_collection_for_select(current_customer.addresses, :id, :address_display)  %></p>
    <p>
     <%= f.radio_button :address_number, 3 %>
     <%= f.label :address, "新しいお届け先" %>
     <p>
      <%= f.label :postal_code, "郵便番号（ハイフンなし）" %>
      <%= f.text_field :postal_code %>
     </p>
     <p>
      <%= f.label :address, "住所　　　　　　　　　　" %>
      <%= f.text_field :address %>
     </p>
     <p>
      <%= f.label :name, "宛名　　　　　　　　　　" %>
      <%= f.text_field :name %>
     </p>
    </p>
    <%= f.submit '確認画面へ進む' %>
    <% end %>
    </table>
   </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
     <h4>注文履歴詳細</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <strong>注文情報</strong>
      <table class="table table-striped">
        <tr>
          <td>注文日</td>
          <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <td>配送先</td>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <td>支払い方法</td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td><%= @order.status_i18n %></td>
        </tr>
      </table>
    </div>
    <div class="col-lg-4">
      <strong>請求情報</strong>
      <table class="table table-striped">
        <tr>
          <td>商品合計</td>
          <td><%= @subtotal.round.to_s(:delimited)%></td>
        </tr>
        <tr>
          <td>配送料</td>
          <td>800円</td>
        </tr>
        <tr>
          <td>ご請求額</td>
          <td><%= @total.round.to_s(:delimited)%></td>
        </tr>
      </table>
    </div>
  </div>
</div>