config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  get "/about", to: "homes#about"
  get "/admin", to: "admin/homes#top"


  devise_for :customers,skip: [:passwords,], controllers: {
    sessions:      'customer/sessions',
    registrations: 'customer/registrations'
    }


  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions:      'admin/sessions',
    }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope module: :customer do
    get "customers/my_page" => "customers#show", as: "my_page"
    post "orders/comfirm" => "orders#comfirm"
    get "orders/comfirm" => "orders#comfirm"
    #post "orders/create" => "orders#create", as: "orders/complete"
    get "orders/complete" => "orders#complete"
    post "orders/complete" => "orders#complete"
    post "orders/new" => "orders#new"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    delete "cart_items/destroy" => "cart_items#destroy"
    get "item/index" => "items#serch",as: "serch"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    patch "addresses/:id/edit" => "addresses#edit"
    resources :items,only: [:index,:show,:delete,:update]
    resources :customers,only: [:show,:edit,:update,:unsubscribe,:withdraw]
    resources :addresses,only: [:index,:create,:edit,:destroy,:update]
    resources :cart_items,only: [:index,:create,:update,:destroy]
    resources :orders,only: [:new,:create,:index,:show]
  end

   namespace :admin do
    resources :homes,only: [:top]
    resources :genres,only: [:index,:show, :edit, :update,:create]
    resources :items,only: [:new,:index,:create,:show,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show]
  end
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  def sum_of_price
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :addresses

  has_many :orders

  def full_name
    this.last_name + this.first_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { wait_payment: 0, confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }

  def subtotal
    price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @subtotal = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
    @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal } + 800
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_out_path_for(resource_or_scope)
    return new_admin_session_path if resource_or_scope == :admin
    root_path
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  def new
    @order = Order.new
    @customer = current_customer
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @subtotal = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
    @total = @order.order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal } + 800
  end

  def comfirm
    @order = Order.new(order_params)
    if params[:order][:address_number] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_number] == "2"
      address = Address.find(params[:order][:address_id])
      @order.postal_code = address.postal_code
      @order.address = address.address
      @order.name = address.name
    elsif params[:order][:address_number] == "3"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
      @address = Address.new(
                  postal_code: params[:order][:postal_code],
                  address: params[:order][:address],
                  name: params[:order][:name],
                  customer_id: current_customer.id
                  )
      @address.save
    end
    @cart_items = CartItem.where(customer_id: current_customer.id)
    @subtotal = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price } + 800
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = Order.new(order_params)
    @customer = current_customer
    @order.customer_id = current_customer.id
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart_item.amount
        order_detail.price = cart_item.item.price
        order_detail.save!
      end
       cart_items.destroy_all
       redirect_to orders_complete_path
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def complete
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :total_payment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @items = Item.all.order(created_at: :desc)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12"><h4>注文履歴詳細</h4></div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped">
        <tr>
          <td><strong>購入者</strong></td>
          <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
        </tr>
        <tr>
          <td><strong>注文日</strong></td>
          <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <td><strong>配送先</strong></td>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <td><strong>支払方法</strong></td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <td><strong>注文ステータス</strong></td>
          <td><%= @order.status_i18n %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <table class="table table-striped">
        <thead>
         <tr>
          <td>商品名</td>
          <td>単価（税込）</td>
          <td>数量</td>
          <td>小計</td>
          <td>製作ステータス</td>
          <td></td>
         </tr>
        </thead>
        <tbody>
         <% @order_details.each do |order_detail| %>
          <tr>
           <td><%= order_detail.item.name %></td>
           <td><%= order_detail.price %></td>
           <td><%= order_detail.amount %></td>
           <td><%= order_detail.subtotal %></td>
           <td>
             <%#= form_with(model: order_detail, url: admin_order_path, local: true, class: "form-row") do |f| %>
             <%#= f.select :making_status, OrderDetail.making_statuses_i18n.invert, {prompt: false}, class:"form-control form-control-sm col-6"  %>
             <%#= f.submit "更新" %>
             <%# end %>
           </td>
           <td></td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-4">
      <table class="table table-striped">
        <tr>
          <td>商品合計</td>
          <td><%= @subtotal.round.to_s(:delimited)%></td>
        </tr>
        <tr>
          <td>送料</td>
          <td>800円</td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td><%= @total.round.to_s(:delimited)%></td>
        </tr>
      </table>
    </div>
  </div>
</div>